export { vsButton, vsButtonGroup } from './vsButton'
export { vsSelect, vsSelectOption, vsSelectOptionGroup } from './vsSelect'
export { default as vsSwitch } from './vsSwitch'
export { default as vsCheckbox } from './vsCheckBox'
export { default as vsRadio } from './vsRadio'
export { default as vsInput } from './vsInput'
export { default as vsTabs } from './vsTabs'
export { default as vsSlider } from './vsSlider'
export { default as vsInputNumber } from './vsInputNumber'
export { default as vsTooltip } from './vsTooltip'
export { default as vsUpload } from './vsUpload'
export { default as vsPopup } from './vsPopup'
export { default as vsAlert } from './vsAlert'
export { vsChip, vsChips } from './vsChip'
export { default as vsProgress } from './vsProgress'
export { vsCard, vsCardGroup } from './vsCard'
export { default as vsList } from './vsList'
export { default as vsAvatar } from './vsAvatar'
export { default as vsPagination } from './vsPagination'
export { default as vsBreadcrumb } from './vsBreadcrumb'

export { default as vsDivider } from './vsDivider'
export { default as vsSpacer } from './vsSpacer'
export { default as vsIcon } from './vsIcon'
export { vsNavbar,vsNavbarGroup, vsNavbarItem } from './vsNavbar'
export { default as notification } from './vsNotifications'
export { vsSidebar, vsSidebarGroup, vsSidebarItem } from './vsSideBar'
export { vsDropDown, vsDropDownItem } from './vsDropDown'
export { default as vsTable } from './vsTable'
export { default as vsDialog } from './vsDialog'
export { default as vsTextarea } from './vsTextarea'
export { vsCollapse, vsCollapseItem} from './vsCollapse'
export { default as vsImages } from './vsImages'
//New Component import

//layout
export { default as vsRow } from '../layout/vsRow'
export { default as vsCol } from '../layout/vsCol'
