declare const _default: {
    name: string;
    linear(t: any, b: any, c: any, d: any): any;
    easeInQuad(t: any, b: any, c: any, d: any): any;
    easeOutQuad(t: any, b: any, c: any, d: any): any;
    easeInOutQuad(t: any, b: any, c: any, d: any): any;
    easeInCubic(t: any, b: any, c: any, d: any): any;
    easeOutCubic(t: any, b: any, c: any, d: any): any;
    easeInOutCubic(t: any, b: any, c: any, d: any): any;
    easeInQuart(t: any, b: any, c: any, d: any): any;
    easeOutQuart(t: any, b: any, c: any, d: any): any;
    easeInOutQuart(t: any, b: any, c: any, d: any): any;
    easeInQuint(t: any, b: any, c: any, d: any): any;
    easeOutQuint(t: any, b: any, c: any, d: any): any;
    easeInOutQuintfunction(t: any, b: any, c: any, d: any): any;
    easeInSine(t: any, b: any, c: any, d: any): any;
    easeOutSine(t: any, b: any, c: any, d: any): any;
    easeInOutSine(t: any, b: any, c: any, d: any): any;
    easeInExpo(t: any, b: any, c: any, d: any): any;
    easeOutExpo(t: any, b: any, c: any, d: any): any;
    easeInOutExpo(t: any, b: any, c: any, d: any): any;
    easeInCirc(t: any, b: any, c: any, d: any): any;
    easeOutCirc(t: any, b: any, c: any, d: any): any;
    easeInOutCirc(t: any, b: any, c: any, d: any): any;
};
export default _default;
